paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Get all products
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful operation
        "404":
          description: Resource not found
        "500":
          description: Internal server error

    post:
      tags:
        - Products
      summary: Create a new product
      security:
        - bearerAuth: []
      requestBody:
        description: Product data
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: Product added successfully
        "200":
          description: Product already added
        "400":
          description: Invalid argument

  /api/products/{pid}:
    get:
      tags:
        - Products
      summary: Get a specific product by ID
      security:
        - bearerAuth: []
      parameters:
        - name: pid
          in: path
          description: ID of the product
          required: true
          type: string
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid argument

    put:
      tags:
        - Products
      summary: Update a specific product by ID
      security:
        - bearerAuth: []
      parameters:
        - name: pid
          in: path
          description: ID of the product
          required: true
          type: string
      responses:
        "201":
          description: Product updated successfully
        "400":
          description: Invalid argument
        "404":
          description: Resource not found

    delete:
      tags:
        - Products
      summary: Delete a specific product by ID
      security:
        - bearerAuth: []
      parameters:
        - name: pid
          in: path
          description: ID of the product
          required: true
          type: string
      responses:
        "200":
          description: Product deleted successfully
        "400":
          description: Invalid argument
